
[terminal]
shell = "D:\\Scoop\\apps\\nu\\current\\nu.exe"

[general]
import = [
  "theme.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 170, lines = 60 }
position = { x = 800, y = 219 }
padding = { x = 20, y = 20 }

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
bold = { family = "Maple Mono NF", style = "Bold" }
italic = { family = "Maple Mono NF", style = "Italic" }
bold_italic = { family = "Maple Mono NF", style = "Bold Italic" }
size = 15
